Exporters:
  - Exporter:
      Type: CSV
      Path: ./export.csv
Categories:
  - Category:
      # all german and english rares and mythics under 5€
      Languages:
        - German
        - English
      Rarities:
        - Rare
        - Mythic
      MaxPrice: 5.0
    PriceStrategy:
      # compare with other german and english offers which condition is max one step worse than yours
      # (e.g. if your card is Near Mint than compare it with Excellent and higher)
      ComparisionAttributes:
        CardLanguage:
          - English
          - German
        SellerCountry: true
        Foil: true
        Signed: true
        Altered: true
        ConditionDeviation: 1
      # offer cards as 5th lowest seller with a minimum price of 10ct
      TargetPrice: Lowest
      MinPrice: 0.1
      Offset: 5
  - Category:
      # all other rares and mythic of different languages which are not foil and under 5€
      Rarities:
        - Rare
        - Mythic
      Foil: false
      MaxPrice: 5.0
    PriceStrategy:
      ComparisionAttributes:
        # don´t check card languages
        CardLanguage: false
        SellerLanguage: true
        Foil: true
        Signed: true
        Altered: true
        Condition: 1
      # offer cards as lowest seller with a minimum price of 10ct
      TargetPrice: Lowest
      Min: 0.1
      Offset: 0
  - Category:
      # all german and english uncommons and commons under 5€
      Languages:
        - German
        - English
      Rarities:
        - Uncommon
        - Common
      MaxPrice: 5.0
    PriceStrategy:
      # compare with other german and english offers which condition is max one step worse than yours
      ComparisionAttributes:
        CardLanguage:
          - English
          - German
        SellerCountry: true
        Foil: true
        Signed: true
        Altered: true
        ConditionDeviation: 1
      # offer cards as 5th lowest seller with a minimum price of 5ct
      TargetPrice: Lowest
      MinPrice: 0.05
      Offset: 5
  - Category:
      # all other uncommons and commons of different languages which are not foil and under 5€
      Rarities:
        - Uncommon
        - Common
      Foil: false
      MaxPrice: 5.0
    PriceStrategy:
      # don´t check card languages
      ComparisionAttributes:
        CardLanguage: false
        SellerCountry: true
        Foil: true
        Signed: true
        Altered: true
        Condition: 1
      # offer cards as lowest seller with a minimum price of 5ct
      TargetPrice: Lowest
      Min: 0.05
      Offset: 0
  - Category:
      # all other rares, mythics, uncommons and commons
      Rarities:
        - Rare
        - Mythic
        - Uncommon
        - Common
    PriceStrategy:
      ComparisionAttributes:
        CardLanguage: true
        SellerLanguage: true
        Foil: true
        Signed: true
        Altered: true
        Condition: 1
      # offer cards as lowest seller
      TargetPrice: Lowest
      Min: 0.1
      Offset: 0

